[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
test = "tests"
ffi = true
fs_permissions = [{ access = "read-write", path = "./"}]
remappings = ["@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts"]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
